//
//  UserAccount.swift
//  MyWorkout
//
//  Created by Lu Ao on 11/4/17.
//  Copyright © 2017 Lu Ao. All rights reserved.
//

import Foundation
import Firebase
import FirebaseAuth
import ReactiveSwift


class UserAccount: NSObject{
    /** Singleton accessor */
    static let userInfo = UserAccount()
    private override init() {
        super.init()
    }
    
    /** Model and security authorization check*/
    private var firUser: User? {
        get {
            return Auth.auth().currentUser
        }
    }
    /** Setup signal for successful sign in */
    private (set) var signedInSignal = MutableProperty<Bool>(false)
    
    var isSignedIn: Bool {
        get {
            if firUser != nil {
                signedInSignal.value = true
                return true
            }
            signedInSignal.value = false
            return false
        }
    }
    
    /** User's unique-autogenerated ID */
    var uid: String? {
        get {
            return firUser?.uid
        }
    }
    
    
    /** Attempt to sign in a user with given credentials */
    func signIn(withEmail email: String, password: String, completion: FirebaseAuth.AuthResultCallback? = nil) {
        Auth.auth().signIn(withEmail: email, password: password, completion: { (user: User?, error: Error?) in
            if let error = error {
                print("Error on login: \(error.localizedDescription)")
                // Error occurred, return with no user and error object
                // TODO: Use self.signedIn(), when logout complete
                self.signedInSignal.value = false
                completion?(nil, error)
            } else {
                // Sign in successful
                // Complete sign-in of user
                self.signedIn()
                completion?(user, error)
            }
        })
    }
    
    /** Complete the sign-in process (called after successful sign-in) */
    func signedIn() {
        // Check that the user is actually signed in already
        if UserAccount.userInfo.isSignedIn {
            // Broadcast signin notification (AppDelegate should pick up and present Root VC)
        } else {
            print("Could not complete login;- no user currently signed in")
        }
    }
    
    
    // TODO: Create User Profile
    /**
     Creates and switches to new user using stock FIRUser and creates a new UserProfile to Database.
     */
    public class func createUser(withEmail email: String, password: String, completion: FirebaseAuth.AuthResultCallback? = nil) {
        // Create stock FIRUser
        Auth.auth().createUser(withEmail: email, password: password, completion: { (newFIRUser: User?, error: Error?) in
            if let error = error {
                print("Error creating new user: \(error.localizedDescription)")
                completion?(nil, error)
            }
            else if let newFIRUser = newFIRUser {
                
                // Create UserProfile (overwrite any existing leaf data)
                //UserProfile.create(UID: newFIRUser.uid, username: userName)
                
                // Complete sign in
                UserAccount.userInfo.signedIn()
                completion?(newFIRUser, error)
            }
        })
    }
    
}
